name: Build GDExtension
on:
  workflow_call:
  workflow_dispatch:

jobs:
  define-matrix:
    runs-on: ubuntu-latest

    outputs:
      matrix-include: ${{ steps.make_matrix.outputs.include }}

    steps:
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Load Matrix
        id: make_matrix
        run: |
          echo 'include='$(python3 make_github_runner_config.py) >> "$GITHUB_OUTPUT"

  build:
    needs: define-matrix
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.define-matrix.outputs.matrix-include) }}

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: 🔗 GDExtension Build
        uses: Ivorforce/godot-cpp-template/.github/actions/build@patch-1
        with:
          platform: ${{ matrix.platform }}
          arch: ${{ matrix.arch }}
          float-precision: ${{ matrix.float_precision }}
          build-target-type: ${{ matrix.build_target_type }}
          gdextension-directory: ''
          em_version: '3.1.55'  # FIXME Doesn't compile on the newest, xtensor has problems
      - name: Mac Sign
        if: ${{ matrix.platform == 'macos' && env.APPLE_CERT_BASE64 }}
        env:
          APPLE_CERT_BASE64: ${{ secrets.APPLE_CERT_BASE64 }}
        uses: godotengine/godot-cpp-template/.github/actions/sign@main
        with:
          FRAMEWORK_PATH: build/addons/numdot/macos/numdot-macos.framework
          APPLE_CERT_BASE64: ${{ secrets.APPLE_CERT_BASE64 }}
          APPLE_CERT_PASSWORD: ${{ secrets.APPLE_CERT_PASSWORD }}
          APPLE_DEV_PASSWORD: ${{ secrets.APPLE_DEV_PASSWORD }}
          APPLE_DEV_ID: ${{ secrets.APPLE_DEV_ID }}
          APPLE_DEV_TEAM_ID: ${{ secrets.APPLE_DEV_TEAM_ID }}
          APPLE_DEV_APP_ID: ${{ secrets.APPLE_DEV_APP_ID }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GDExtension-${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.float_precision }}-${{ matrix.build_target_type }}
          path: |
            ${{ github.workspace }}/build/**
  merge:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: GDExtension-all
          pattern: GDExtension-*
          delete-merged: true
